#!/usr/bin/env bash
# render.sh <env> — pre-render EVERY promotable artifact (per-space Genie space + AI/BI dashboard)
# from the committed dev source to the target env, assert each references only <env>_<domain>
# (S4 + S12 / ADR-0003), AND generate one prod genie_spaces resource per space (per-space promotion).
# Run before `bundle validate/deploy -t <env>`. Config-driven (ADR-0004): FROM_ENV/DOMAIN overridable.
set -euo pipefail
ENV="${1:?usage: render.sh <dev|prod>}"
FROM_ENV="${FROM_ENV:-dev}"
DOMAIN="${DOMAIN:-recebiveis}"

render_one() {  # <src> <out>
  local src="$1" out="$2"
  [ -f "$src" ] || return 0
  mkdir -p "$(dirname "$out")"
  rm -f "$out"   # never deploy a stale build (S4 review)
  python3 scripts/pre_render.py render "$src" --from "$FROM_ENV" --to "$ENV" --domain "$DOMAIN" --out "$out"
  python3 scripts/pre_render.py check "$out" --to "$ENV" --domain "$DOMAIN"
}

# PER-SPACE Genie spaces: each promotion commits its own src/genie/<slug>.serialized_space.json, so we
# render EACH and emit one prod genie_spaces resource per slug. DABs YAML can't loop, so we generate a
# prod-scoped resource file (build/, gitignored) that databricks.yml includes via `build/*.gen.yml`.
mkdir -p build/genie
GEN="build/resources.gen.yml"
shopt -s nullglob
entries=""
for src in src/genie/*.serialized_space.json; do
  slug="$(basename "$src" .serialized_space.json)"
  render_one "$src" "build/genie/${slug}.serialized_space.json"
  # file_path is resolved relative to THIS generated file's dir (build/), so it's ./genie/... not ./build/genie/...
  entries+="        ${slug}:\n"
  entries+="          warehouse_id: \${var.warehouse_id}\n"
  entries+="          file_path: ./genie/${slug}.serialized_space.json\n"
  # Optional per-space title sidecar (committed by the app next to the artifact).
  if [ -f "src/genie/${slug}.title" ]; then
    title="$(tr -d '\n' < "src/genie/${slug}.title" | sed 's/"/\\"/g')"
    entries+="          title: \"${title}\"\n"
  fi
done
{
  echo "# GENERATED by scripts/render.sh — do not edit. One prod genie_spaces resource per promoted"
  echo "# space (per-space promotion). Prod-scoped: dev never deploys genie_spaces (dev is human-authored)."
  echo "targets:"
  echo "  prod:"
  echo "    resources:"
  if [ -n "$entries" ]; then
    echo "      genie_spaces:"
    printf "%b" "$entries"
  else
    echo "      genie_spaces: {}"
  fi
} > "$GEN"
echo "generated $GEN ($(ls src/genie/*.serialized_space.json 2>/dev/null | wc -l | tr -d ' ') space(s))"

# AI/BI dashboard (a separate artifact; its resource stays inline in databricks.yml).
render_one "src/dashboards/recebiveis.lvdash.json" "build/dashboards/recebiveis.lvdash.json"
