#!/usr/bin/env bash
# render.sh <env> — pre-render EVERY promotable artifact (per-space Genie space + AI/BI dashboard)
# from the committed dev source to the target env, assert each references only <env>_<domain>
# (S4 + S12 / ADR-0003), AND generate one prod genie_spaces resource per space (per-space promotion).
# Run before `bundle validate/deploy -t <env>`. Config-driven (ADR-0004): FROM_ENV/DOMAIN overridable.
set -euo pipefail
ENV="${1:?usage: render.sh <dev|prod>}"
FROM_ENV="${FROM_ENV:-dev}"
DOMAIN="${DOMAIN:-recebiveis}"

render_one() {  # <src> <out> [<mapping>]
  local src="$1" out="$2" mapping="${3:-}"
  [ -f "$src" ] || return 0
  mkdir -p "$(dirname "$out")"
  rm -f "$out"   # never deploy a stale build (S4 review)
  python3 scripts/pre_render.py render "$src" --from "$FROM_ENV" --to "$ENV" --domain "$DOMAIN" --out "$out"
  # G7: the promotion's declared table de-para (if any), applied AFTER the rebind — the allowlist
  # check below stays UNWIDENED (unlike rehydrate's G6 preview, which widens for the caller's OWN
  # de-para): a mapped target outside <to_env>_<domain> must FAIL here, that's ENV-01 doing its job.
  if [ -n "$mapping" ] && [ -f "$mapping" ]; then
    python3 scripts/pre_render.py apply-mapping "$out" --mapping "$mapping" --from "$FROM_ENV" --to "$ENV" --domain "$DOMAIN"
  fi
  python3 scripts/pre_render.py check "$out" --to "$ENV" --domain "$DOMAIN"
}

# PER-SPACE Genie spaces: each promotion commits its own src/genie/<slug>.serialized_space.json, so we
# render EACH and emit one prod genie_spaces resource per slug. DABs YAML can't loop, so we generate a
# prod-scoped resource file (build/, gitignored) that databricks.yml includes via `build/*.gen.yml`.
mkdir -p build/genie
GEN="build/resources.gen.yml"
shopt -s nullglob
entries=""
space_count=0
for src in src/genie/*.serialized_space.json; do
  slug="$(basename "$src" .serialized_space.json)"
  space_count=$((space_count + 1))
  render_one "$src" "build/genie/${slug}.serialized_space.json" "src/genie/${slug}.mapping.json"
  # file_path is resolved relative to THIS generated file's dir (build/), so it's ./genie/... not ./build/genie/...
  entries+="        ${slug}:\n"
  entries+="          warehouse_id: \${var.warehouse_id}\n"
  entries+="          file_path: ./genie/${slug}.serialized_space.json\n"
  # Optional per-space title sidecar (committed by the app next to the artifact).
  if [ -f "src/genie/${slug}.title" ]; then
    title="$(tr -d '\n' < "src/genie/${slug}.title" | sed 's/"/\\"/g')"
    entries+="          title: \"${title}\"\n"
    # Copy the title sidecar forward too (F2): apply_access.py resolves the deployed Space's live id
    # by matching this title via genie.list_spaces() (the id isn't in bundle summary / the payload).
    cp "src/genie/${slug}.title" "build/genie/${slug}.title"
  fi
  # Canonical AudienceSpec. A legacy input remains readable only during ADR-0009's bounded
  # compatibility window; canonical content is always materialized at the canonical filename.
  if [ -f "src/genie/${slug}.audience.json" ]; then
    cp "src/genie/${slug}.audience.json" "build/genie/${slug}.audience.json"
  elif [ -f "src/genie/${slug}.access.json" ]; then
    # Read-only legacy input until the content-repo atomic switch (ADR-0009).
    cp "src/genie/${slug}.access.json" "build/genie/${slug}.access.json"
  fi
done
{
  echo "# GENERATED by scripts/render.sh — do not edit. One prod genie_spaces resource per promoted"
  echo "# space (per-space promotion). Prod-scoped: dev never deploys genie_spaces (dev is human-authored)."
  echo "targets:"
  echo "  prod:"
  echo "    resources:"
  if [ -n "$entries" ]; then
    echo "      genie_spaces:"
    printf "%b" "$entries"
  else
    echo "      genie_spaces: {}"
  fi
} > "$GEN"
echo "generated $GEN (${space_count} space(s))"

# AI/BI dashboard (a separate artifact). After the S9b repo split the dashboard RESOURCE is no longer
# inline in databricks.yml (which would break a standalone app-repo `bundle validate` — no content, no
# built artifact). Instead it's GENERATED here into build/resources.gen.yml (the same include the genie
# spaces use), guarded on the source existing: with a content overlay it's emitted + deploys; standalone
# (no src/dashboards) it's simply omitted — a clean no-op. file_path is relative to the generated file's
# dir (build/), so ./dashboards/... not ./build/dashboards/...
render_one "src/dashboards/recebiveis.lvdash.json" "build/dashboards/recebiveis.lvdash.json"
if [ -f "build/dashboards/recebiveis.lvdash.json" ]; then
  {
    echo "      dashboards:"
    echo "        recebiveis_painel:"
    echo "          display_name: \"Painel de Recebíveis — Volume por Bandeira\""
    echo "          warehouse_id: \${var.warehouse_id}"
    echo "          file_path: ./dashboards/recebiveis.lvdash.json"
  } >> "$GEN"
  echo "appended dashboard resource to $GEN"
fi

# Setup job (seeds synthetic demo data): also GENERATED (was resources/setup.job.yml, removed in the
# split — its notebook src/setup/seed_recebiveis.py is content, absent from a standalone app checkout).
# Emitted into its own build/*.gen.yml (picked up by the same `build/*.gen.yml` include) only when the
# notebook exists under overlay; standalone it's a comment-only stub. The job spec is byte-identical to
# the old resources/setup.job.yml — INCLUDING no target scoping, so it applies to whichever target is
# deployed (dev AND prod, exactly as before). `../src/setup/...` resolves the same from build/ as it did
# from resources/ (both are one level under the repo root).
SETUP_NB="src/setup/seed_recebiveis.py"
SETUP_GEN="build/setup.gen.yml"
if [ -f "$SETUP_NB" ]; then
  cat > "$SETUP_GEN" << 'YAML'
# GENERATED by scripts/render.sh — do not edit. Setup job (synthetic seed) for the demo domain.
# Un-scoped (applies to all targets), matching the pre-split resources/setup.job.yml exactly.
resources:
  jobs:
    setup:
      name: "[${bundle.target}] recebiveis-setup"
      max_concurrent_runs: 1
      tasks:
        - task_key: seed_recebiveis
          notebook_task:
            notebook_path: ../src/setup/seed_recebiveis.py
            base_parameters:
              catalog: "${var.env}_${var.domain}"
              env: "${var.env}"
YAML
  echo "generated $SETUP_GEN (setup job included)"
else
  echo "# GENERATED by scripts/render.sh — no content overlay, setup job omitted" > "$SETUP_GEN"
  echo "generated $SETUP_GEN (no src/setup — stub only)"
fi
